### PR TITLE
Use Redis for PHP session handler

### PR DESCRIPTION
**Pull request by Omicron7**
This adds redis as a PHP session handler. Both WordPress and phpCAS use the underlying php session, so this will work for both.

### CODE REVIEW

**Comment by Omicron7** [comment]
@twinge You want to look at this or should I just merge it?

**Comment by twinge** [comment]
I was just looking at the data on the redis server and do have one question. Is this using SETEX (https://redis.io/commands/setex)? If not, is there some other mechanism for expiring/deleting old keys? 

I know the key session will expire, so this isn't a security concern, it's a garbage collection concern. We have this problem in our rails apps.

**Comment by Omicron7** [comment]
I believe it does: https://github.com/phpredis/phpredis#php-session-handler

> Sessions have a lifetime expressed in seconds and stored in the INI variable "session.gc_maxlifetime". You can change it with ini_set(). The session handler requires a version of Redis with the SETEX command (at least 2.0).

`session.gc_maxlifetime`might not be set.

I set the session handlers in wp-config.php, the other option would of been to set them in the php redis.ini by using `RUN echo 'config.setting' >> redis.ini` The wp-config.php would set the session handler for any wordpress pages whereas the second would set it globally for all of php. Didn't know at what level you would want this, so just picked the wp-config one.

**Comment by twinge** [comment]
`session.gc_maxlifetime` has a default of 1440 seconds (http://php.net/manual/en/session.configuration.php). That's probably a bit on the short side.

**Pull request merged**
